// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/barber-hero/Cinematic.tsx": () => import("../components/mockups/barber-hero/Cinematic.tsx"),
  "./components/mockups/barber-hero/Compact.tsx": () => import("../components/mockups/barber-hero/Compact.tsx"),
  "./components/mockups/barber-hero/CoverAvatar.tsx": () => import("../components/mockups/barber-hero/CoverAvatar.tsx"),
  "./components/mockups/customer-view/VariantBolimli.tsx": () => import("../components/mockups/customer-view/VariantBolimli.tsx"),
  "./components/mockups/customer-view/VariantKartochkali.tsx": () => import("../components/mockups/customer-view/VariantKartochkali.tsx"),
  "./components/mockups/customer-view/VariantMinimalist.tsx": () => import("../components/mockups/customer-view/VariantMinimalist.tsx")
};
